### ISSUE TITLE
Do I need the eCozy Central Unit if I use the SmartThings hub?

### ISSUE THREAD

**Issue by FezVrasta** [ckpt-martin/SmartThings#1]
As title, do I need the Central Unit or are the valves enough?

**Comment by sh-guy** [comment]
No. The eCozy can only connect to either the CU or ST. I have 9 eCozy TRVs connected to just my ST hub. 
I did purchase the kit with the CU just in case I needed it for something in the future or in case I didn‘t get them working with ST like I wanted. But, they work just fine with the ST hub, so my CU is still in the box unused.
As soon as I get around to creating a SmartApp for this as well, we will also be able to load a 7-day temperature schedule directly into the TRV. Then there will be almost nothing the CU can do that we can‘t also do with the ST hub.
And currently I am using standard ST automation to control the TRV when a window/door opens or closes since the integrated open window feature doesn‘t work for me (probably based on the placement of the radiators). But this standard automation has a drawback that it sets static temperatures that are set in the rule. If you manually set the temperature to something else, then the next time the window is opened and closed it is set back to that static temperature setting. So, I want to add support for external sensors in my SmartApp so that it can remember what temperature was set before it changed and return back to that temperature again. That will also be important when scheduling can be loaded as those temperatures would need to be considered when the window closes again. So, I think the SmartApp will be important. But for now the DTH does the job for me until I get to the SmartApp.
